# 🟦 Data Preprocessing: Scaling, Encoding, Normalization (with scikit-learn)

## Concept: What is Data Preprocessing?

Data preprocessing transforms raw data into a clean and usable format.

It improves model performance and training speed.

### Common tasks:

- Handling missing values
- Scaling numerical features
- Encoding categorical variables
- Normalizing feature ranges

# 1️⃣ Feature Scaling

Scaling adjusts values so features contribute equally.

**Common techniques:** StandardScaler (Z-score), MinMaxScaler (0-1 scale)

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler , MinMaxScaler
numeric_data = pd.DataFrame({
    "Salary" : [30000 , 45000 , 60000 , 80000 , 120000],
    "Age" : [25 , 32, 47, 51, 62]
})
numeric_data

   Salary  Age
0   30000   25
1   45000   32
2   60000   47
3   80000   51
4  120000   62

In [3]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler
#Standard Scaling(Z-Score)
std_scaler = StandardScaler()
scaled_std = std_scaler.fit_transform(numeric_data)
df = pd.DataFrame(scaled_std , columns = numeric_data.columns)
print("\nStandard Scaled Data\n", df)

Standard Scaled Data
      Salary       Age
0 -1.184341 -1.382872
1 -0.704203 -0.856780
2 -0.224065  0.270562
3  0.416120  0.571186
4  1.696489  1.397904

In [4]:
numeric_data

   Salary  Age
0   30000   25
1   45000   32
2   60000   47
3   80000   51
4  120000   62

# `fit_transform()` does two steps at once:

- **`fit()`**: Learns the mean & standard deviation of your data.

- **`transform()`**: Applies the scaling (converts data to Z-scores).

**For `StandardScaler`: Each feature becomes mean = 0, std = 1.**

# Z-Score

How many standard deviations away each value is from the mean.

### Example:

If an employee's age is 75 in a class where:

**Mean = 70**

**Standard deviation = 5**

**Z-score = (75 - 70) / 5 = +1.0**

**(+1.0 means 1 standard deviation above average)**

# Min-Max Scaling (0 to 1)

In [7]:
minmax_scaler = MinMaxScaler()
scaled_minmax = minmax_scaler.fit_transform(numeric_data)
print("\nMin-Max Scaled Data:\n", pd.DataFrame(scaled_minmax , columns = numeric_data.columns))

Min-Max Scaled Data:
      Salary       Age
0  0.000000  0.000000
1  0.166667  0.189189
2  0.333333  0.594595
3  0.555556  0.702703
4  1.000000  1.000000

# Min-Max Scaling

**Formula:**

`X_scaled = (X - X_min) / (X_max - X_min)`

### Example:

**1st value of Age:**

`→ (25 - 25) / (62 - 25) = 0`

**2nd value of Age:**

`→ (32 - 25) / (62 - 25) = 0.18`

# StandardScaler vs. MinMaxScaler Ranges

| Scaler | Typical Range | What It Means |
|---|---|---|
| **MinMaxScaler** | `[0, 1]` | "Squeezes data into a fixed 0–1 box." |
| **StandardScaler** | No fixed range! | "Centers data around 0; most values fall between -3 to +3 (99% of data)." |

# 2️⃣ Encoding Categorical Variables

Convert text labels to numeric format for ML models.

In [8]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
#sample data
cat_data = pd.DataFrame({
    "Department" : ['HR','Sales','IT','HR','IT']
})
cat_data

  Department
0         HR
1      Sales
2         IT
3         HR
4         IT

# Label Encoding

In [9]:
label_encoder = LabelEncoder()
cat_data['Dept_label'] = label_encoder.fit_transform(cat_data['Department'])
print("\nLabel Encoder:\n", cat_data)

Label Encoder:
   Department  Dept_label
0         HR           0
1      Sales           2
2         IT           1
3         HR           0
4         IT           1

# `fit_transform()` does two steps at once:

- **`fit()`**: Learns all unique categories in the column.

- **`transform()`**: Converts each category to a number (e.g., HR → 0, IT → 1).

# One-Hot Encoding - alternative to label encoder

In [10]:
cat_data_ohe = pd.get_dummies(cat_data["Department"], prefix = 'Dept')
print("\nOne-Hot Encoded:\n\n", cat_data_ohe)

One-Hot Encoded:

    Dept_HR  Dept_IT  Dept_Sales
0     True    False       False
1    False    False        True
2    False     True       False
3     True    False       False
4    False     True       False

Converts each category into a binary column (1 if present, 0 otherwise).

**Example:** `'HR'` → Dept_IT=0, Dept_HR=1, Dept_Admin=0.

**Example:** `'IT'` → Dept_IT=1, Dept_HR=0, Dept_Admin=0.

# LabelEncoder vs. One-Hot Encoding

## LabelEncoder

- **Output:** `['HR', 'IT'] → [0, 1]`
- **Use for:** Target (`y`) only
- **Never use for:** Features (creates false order)

## One-Hot (`get_dummies`)

- **Output:** `'HR' → [1, 0]`, `'IT' → [0, 1]`
- **Use for:** Features (`X`)
- **Avoid when:** >15 categories

# 3️⃣ Normalization

Normalize data such that row vector magnitudes = 1.

## Why Use Normalizer?

### Purpose:

Scales each row to have a unit magnitude (length = 1) while preserving direction.

# Key Idea:

Converts row vectors into "pure direction" form by dividing by their Euclidean norm (`√(x₁² + x₂² + ...)`).

## When to Use:

- **Text data** (TF-IDF, word counts)
- **Clustering** (k-means, cosine similarity)
- Any algorithm sensitive to vector magnitudes but not their lengths (e.g. NLP, recommender systems).

In [11]:
from sklearn.preprocessing import Normalizer
#Example data
x = np.array([[3.0,4.0], [1.0,0.0], [0.0,8.0]])
print("\nOriginal Data:\n",x)

Original Data:
 [[3. 4.]
 [1. 0.]
 [0. 8.]]

In [12]:
normalizer = Normalizer()
normalized_data = normalizer.fit_transform(x)
print("\nNormalized Data\n\n", normalized_data)

Normalized Data

 [[0.6 0.8]
 [1.  0. ]
 [0.  1. ]]

# How It Works

For each row, the Normalizer computes the Euclidean norm (magnitude):

`norm = sqrt(x₁² + x₂² + ...)`

Divides each element by the norm:

`x₁_normalized = x₁ / norm, x₂_normalized = x₂ / norm`

### Calculates Row Norm:

For `[3, 4]` → `norm = √(3² + 4²) = 5`

### Divides Each Element by Norm:

`[3/5, 4/5] = [0.6, 0.8]`

**Now the row has length 1.**

# Normalization Examples

### 1. First Row `[3.0, 4.0]`

- **Norm:** `√(3² + 4²) = √(9 + 16) = 5`
- **Normalized:** `[3/5, 4/5] = [0.6, 0.8]`

### 2. Second Row `[1.0, 0.0]`

- **Norm:** `√(1² + 0²) = 1`
- **Normalized:** `[1/1, 0/1] = [1.0, 0.0]`

### 3. Third Row `[0.0, 8.0]`

- **Norm:** `√(0² + 8²) = 8`
- **Normalized:** `[0/8, 8/8] = [0.0, 1.0]`

# Why Not MinMax/StandardScaler?

MinMax/StandardScaler compare features across rows (columns),

but Normalizer scales each row (sample) to focus on relative feature proportions.

# 🏢 Case Study: Retail Customer Data

### Scenario:
You have a retail customer dataset with income, age, and gender.

You want to prepare it for ML model input.

In [13]:
raw_data = pd.DataFrame({
    'CustomerID': [101, 102, 103, 104, 105],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'Age': [23, 45, 31, 35, 52],
    'Income': [25000, 52000, 38000, 45000, 61000]
})

print("\nOriginal Retail Data:\n", raw_data)

Original Retail Data:
    CustomerID  Gender  Age  Income
0         101    Male   23   25000
1         102  Female   45   52000
2         103  Female   31   38000
3         104    Male   35   45000
4         105  Female   52   61000

In [14]:
#Drop ID (not useful for training)
data = raw_data.drop(columns = 'CustomerID')
data

   Gender  Age  Income
0    Male   23   25000
1  Female   45   52000
2  Female   31   38000
3    Male   35   45000
4  Female   52   61000

In [16]:
#Encoding the gender
label_encoder = LabelEncoder()
raw_data['Gender'] = label_encoder.fit_transform(raw_data['Gender'])
print("\n Gender Label Encoded\n\n", raw_data)

 Gender Label Encoded

    CustomerID  Gender  Age  Income  Gender_label
0         101       1   23   25000             1
1         102       0   45   52000             0
2         103       0   31   38000             0
3         104       1   35   45000             1
4         105       0   52   61000             0

In [17]:
datar = raw_data.drop(columns = 'Gender_label')
datar

   CustomerID  Gender  Age  Income
0         101       1   23   25000
1         102       0   45   52000
2         103       0   31   38000
3         104       1   35   45000
4         105       0   52   61000

In [22]:
# Scale age and income
minmax_scaler = MinMaxScaler()
scaled = minmax_scaler.fit_transform(raw_data[['Age','Income']])
raw_data[['Age','Income']] = scaled

print("\nProcessed Retail Data:\n",raw_data)

Processed Retail Data:
    CustomerID  Gender       Age    Income  Gender_label
0         101       1  0.000000  0.000000             1
1         102       0  0.758621  0.750000             0
2         103       0  0.275862  0.361111             0
3         104       1  0.413793  0.555556             1
4         105       0  1.000000  1.000000             0

# Summary

**Scaling (StandardScaler):** Transforms features to mean=0, std=1 for consistent magnitudes.

**Encoding (LabelEncoder/OneHot):** Converts categories to numbers (labels) or binary columns (one-hot).

**Normalization (Normalizer):** Scales each row to unit magnitude (length=1) for direction-focused analysis.